"""
Django settings for djoknone_portfolio project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-jgdga4)no8-7t(8+fosa^fp9n!wo^5x1keij*y)@y&*cee$4zl"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djoknone_portfolio.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djoknone_portfolio.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ***************************************************************
# CONFIGURATION DE LA BASE DE DONNÉES (DOCKER / DEV)
# ***************************************************************

# La configuration est conditionnelle : 
# Si la variable d'environnement 'DB_HOST' est définie (par docker-compose.yml), on utilise PostgreSQL.
if os.environ.get('DB_HOST'):
    # Configuration PostgreSQL pour l'environnement Docker/Production (professionnel)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),  # Sera 'db' (le nom du service) dans le réseau Docker
            'PORT': os.environ.get('DB_PORT'),
        }
    }
else:
    # Configuration SQLite par défaut (pour le développement local simple hors Docker)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# ***************************************************************
# INTERNATIONALISATION (i18n) et LOCALISATION
# ***************************************************************

# Langue principale du site : Français (fr-fr)
LANGUAGE_CODE = "fr-fr" 

# Fuseau horaire. 'UTC' est sûr.
TIME_ZONE = "UTC" 

# Active le système de traduction de Django (préparation pour le multilingue futur)
USE_I18N = True 

# Active la gestion des fuseaux horaires (recommandé)
USE_TZ = True



# ***************************************************************
# FICHIERS STATIQUES (CSS, JS, Images)
# ***************************************************************

# URL utilisée pour accéder aux fichiers statiques (ex: /static/styles.css)
STATIC_URL = "static/"

# Dossier où Django va collecter tous les fichiers statiques pour le déploiement (production)
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"