# Generated by Django 5.2.8 on 2025-12-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "headline",
                    models.CharField(
                        help_text="Ex: Statisticien | Data Analyst | Développeur Python",
                        max_length=200,
                        verbose_name="Titre professionnel",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Présentation détaillée (Markdown supporté)",
                        verbose_name="Biographie",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile/",
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email de contact"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Localisation"
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub")),
                ("twitter_url", models.URLField(blank=True, verbose_name="Twitter/X")),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "website_url",
                    models.URLField(blank=True, verbose_name="Site web personnel"),
                ),
                (
                    "cv_file",
                    models.FileField(
                        blank=True, null=True, upload_to="cv/", verbose_name="CV (PDF)"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Affiche un badge 'Disponible' sur le site",
                        verbose_name="Disponible pour opportunités",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil",
                "verbose_name_plural": "Profil",
            },
        ),
    ]
