# Generated by Django 5.2.8 on 2025-12-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la certification"
                    ),
                ),
                (
                    "issuer",
                    models.CharField(max_length=200, verbose_name="Organisme émetteur"),
                ),
                (
                    "issuer_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certifications/",
                        verbose_name="Logo de l'organisme",
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID de certification"
                    ),
                ),
                (
                    "credential_url",
                    models.URLField(blank=True, verbose_name="Lien de vérification"),
                ),
                ("issue_date", models.DateField(verbose_name="Date d'obtention")),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si pas d'expiration",
                        null=True,
                        verbose_name="Date d'expiration",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["order", "-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200, verbose_name="Diplôme")),
                (
                    "field_of_study",
                    models.CharField(max_length=200, verbose_name="Domaine d'études"),
                ),
                (
                    "institution",
                    models.CharField(max_length=200, verbose_name="Établissement"),
                ),
                (
                    "institution_url",
                    models.URLField(
                        blank=True, verbose_name="Site web de l'établissement"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si en cours",
                        null=True,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="En cours"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Détails sur la formation, mentions, etc.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
                "ordering": ["-is_current", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Poste")),
                (
                    "company",
                    models.CharField(
                        max_length=200, verbose_name="Entreprise / Organisation"
                    ),
                ),
                (
                    "company_url",
                    models.URLField(
                        blank=True, verbose_name="Site web de l'entreprise"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("work", "Emploi"),
                            ("internship", "Stage"),
                            ("freelance", "Freelance"),
                            ("volunteer", "Bénévolat"),
                        ],
                        default="work",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Missions et réalisations (Markdown supporté)",
                        verbose_name="Description",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si poste actuel",
                        null=True,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Poste actuel"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Expérience",
                "verbose_name_plural": "Expériences",
                "ordering": ["-is_current", "-start_date"],
            },
        ),
    ]
