# Generated by Django 5.2.8 on 2025-12-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Couleur HEX (ex: #3B82F6)",
                        max_length=7,
                        verbose_name="Couleur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technologie",
                "verbose_name_plural": "Technologies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        help_text="Résumé en une ou deux phrases (affichée dans les cartes)",
                        max_length=300,
                        verbose_name="Description courte",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description détaillée du projet (Markdown supporté)",
                        verbose_name="Description complète",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/",
                        verbose_name="Image de couverture",
                    ),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="Lien GitHub")),
                ("demo_url", models.URLField(blank=True, verbose_name="Lien Démo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("archived", "Archivé"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Afficher en avant sur la page d'accueil",
                        verbose_name="Projet vedette",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        related_name="projects",
                        to="app_projects.technology",
                        verbose_name="Technologies utilisées",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["-is_featured", "order", "-created_at"],
            },
        ),
    ]
